# Generated by Django 5.0 on 2024-02-10 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Business',
            new_name='Industry',
        ),
        migrations.AlterModelOptions(
            name='industry',
            options={'verbose_name': 'industry', 'verbose_name_plural': 'industries'},
        ),
        migrations.RenameField(
            model_name='company',
            old_name='business',
            new_name='industry',
        ),
    ]
