# Generated by Django 5.0 on 2024-01-03 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgement',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='userscoremodifierinstance',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userscoremodifierinstance',
            name='modifier_type',
        ),
        migrations.DeleteModel(
            name='ClientUser',
        ),
        migrations.DeleteModel(
            name='UserScoreModifierInstance',
        ),
        migrations.DeleteModel(
            name='UserScoreModifierType',
        ),
    ]
